name: Lint for front

on:
  push:
    branches:
      - "fe_fix_*"
      - "fe_feature_*"
      - "fe_release_*"

jobs:
  lint-code:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16

      - name: Install dependencies and lint code
        run: |
          cd PIF_PAF-front
          pwd
          npm install
          npm run lint --prefix .

      # - name: Run Lint 
      #   run: |
      #     cd PIF_PAF-front
      #     pwd
          
      
      
    