name: Test and Coverage

on:
  push:
    branches:
      - 'be_fix_*'
      - 'be_feature_*'
      - 'be_release_*'  

jobs:
  back-end_test-and-coverage:
    runs-on: ubuntu-22.04

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DB_HOST: localhost
          MYSQL_DB_PORT: 3310
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: rdv
          MYSQL_USER: student
          MYSQL_PASSWORD: student
        ports:
          - 3310:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if pull request was merged
        run: |
          if [ "${{ github.event.pull_request.merged }}" == "true" ]; then
            echo "Pull request was merged, go to bump version."
            exit 0
          else
            echo "Pull request was not merged, no bump version."
            exit 1
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Check coverage thresholds
        run: npm run check-coverage-thresholds

      - name: Upload coverage to Coveralls
        run: npm run coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}